version: '3.8'

services:
  web:
    build:
      context: .
      target: dev
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
    environment:
      - APPLICATION_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=app
      - DB_USER=app
      - DB_PASSWORD=app
    depends_on:
      - mysql
  mysql:
    image: mysql:8.4
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
